[project]
name = 'STXBazaar'
description = 'Bitcoin-Native Vault & Time-Lock Protocol on Stacks L2'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.vault]
path = 'contracts/vault.clar'
clarity_version = 3
epoch = '3.0'

[contracts.stxbazaar-lockengine-beta]
path = 'contracts/lock-engine.clar'
clarity_version = 3
epoch = '3.0'

[contracts.stxbazaar-yieldadapter-beta]
path = 'contracts/yield-adapter.clar'
clarity_version = 3
epoch = '3.0'

[contracts.lock-engine-trait]
path = 'contracts/lock-engine-trait.clar'
clarity_version = 3
epoch = '3.0'

[contracts.yield-strategy-trait]
path = 'contracts/yield-strategy-trait.clar'
clarity_version = 3
epoch = '3.0'

[contracts.mock-yield-strategy]
path = 'contracts/mock-yield-strategy.clar'
clarity_version = 3
epoch = '3.0'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
